#!/usr/bin/env python3
# JIT Network Access - Copyright (C) 2026 Slopapalooza
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Authoritative reference implementation + conformance-vector generator for the
JIT Network Access portable core (L3).

This is the "third witness": an independent implementation of the byte-level
constructions (PAE, canonicalization, the proof HMAC, the stateless nonce) that
the Lua and Go reference libraries MUST match, byte for byte. The vectors it
emits (vectors.json) are the shared contract; any adapter that diverges fails
conformance.

Run:  python generate_vectors.py            # writes vectors.json next to this file
      python generate_vectors.py --check    # regenerate in memory and diff vs the file

Deterministic: all "random" inputs are fixed test values, so output is stable
and reviewable in git. Nothing here uses os.urandom.
"""

import argparse
import base64
import hashlib
import hmac
import ipaddress
import json
import os
import sys

# The byte-level constructions live in the shared reference module (core/py)
# so this generator and the knock client cannot drift. jitcrypto is validated
# against the very vectors this file emits (run with --check).
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "py"))
from jitcrypto import (  # noqa: E402
    PROOF_DOMAIN, NONCE_DOMAIN, b64u, b64u_dec, le64, pae,
    canon_server_name, canon_ip, proof_canonical, build_proof, verify_proof,
    nonce_mac_input, build_nonce, verify_nonce,
)

# ---------------------------------------------------------------------------
# Vector generation
# ---------------------------------------------------------------------------

def hexs(b: bytes) -> str:
    return b.hex()

def classify_rejection(addr: str) -> str:
    """A stable reason label, independent of any language's error wording."""
    parts = addr.split(".")
    if len(parts) == 4 and all(q.isdigit() for q in parts):
        if any(len(q) > 1 and q.startswith("0") for q in parts):
            return "ipv4-leading-zero"
        if any(int(q) > 255 for q in parts):
            return "ipv4-octet-out-of-range"
    if "%" in addr:
        return "zoned-address"
    return "unparseable"


def build_vectors() -> dict:
    v = {
        "_comment": "Conformance vectors for JIT Network Access L3. Generated by "
                    "generate_vectors.py. Lua and Go reference libs MUST reproduce "
                    "every output below byte-for-byte. Do not hand-edit.",
        "constants": {
            "proof_domain": PROOF_DOMAIN.decode(),
            "nonce_domain": NONCE_DOMAIN.decode(),
            "hash": "SHA-256",
            "nonce_len_bytes": 56,
            "encoding": "base64url-nopad",
        },
        "pae": [],
        "canon_server_name": [],
        "canon_ip": [],
        "proof": [],
        "nonce": [],
    }

    # --- PAE ---
    pae_cases = [
        [],
        [b""],
        [b"", b""],
        [b"jitaccess-v1"],
        [b"a", b"bb", b"ccc"],
        # the classic canonicalization-collision pair must NOT collide under PAE:
        [b"aa", b"bb"],
        [b"aab", b"b"],
    ]
    for pieces in pae_cases:
        v["pae"].append({
            "pieces": [b64u(p) for p in pieces],
            "pieces_utf8": [p.decode("latin-1") for p in pieces],
            "out_hex": hexs(pae(pieces)),
        })

    # --- server_name canonicalization ---
    for host in ["grafana.example.com", "Grafana.Example.COM", "grafana.example.com.",
                 "grafana.example.com:8443", "GRAFANA.example.com.:443",
                 "wiki.internal", "xn--caf-dma.example.com", "9wiki.internal",
                 # PROTOCOL §4 step 1 — bracketed IPv6 literals. Unpinned until
                 # now, and the Lua reference had already diverged: it returned
                 # the bracket contents WITHOUT trimming, so "[ ::1 ]" produced a
                 # different MAC input and a different grant key than Python/Go
                 # for the same client.
                 "[2001:db8::1]", "[2001:DB8::1]:8443", "[ ::1 ]", "[::1]",
                 # whitespace around the whole value
                 "  grafana.example.com  "]:
        v["canon_server_name"].append({"in": host, "out": canon_server_name(host)})

    # --- ip canonicalization ---
    ip_cases = [
        ("1.2.3.4", 128, 32),
        ("192.168.001.005", 128, 32),           # ipaddress rejects leading zeros -> see note
        ("2001:db8:0:0:0:0:0:1", 128, 32),
        ("2001:0DB8::1", 128, 32),
        ("::ffff:1.2.3.4", 128, 32),            # v4-mapped normalizes to v4
        ("2001:db8:abcd:1234::1", 64, 32),      # /64 grant -> network address
        ("2001:db8:abcd:1234:5678::9", 64, 32),
        # Rejections the Lua core was tightened to match (Go/Python already
        # refuse all of these). Unpinned, one engine could quietly start keying a
        # grant on an address the others refuse outright — the exact cross-engine
        # divergence the vector file exists to prevent.
        ("::ffff:01.2.3.4", 128, 32),   # leading zero inside an IPv4-in-IPv6 literal
        ("1::2::3", 128, 32),           # more than one "::" is ambiguous
        ("2001:db8:::1", 128, 32),      # malformed run of colons
        (":2001:db8::1", 128, 32),      # stray leading colon
        ("2001:db8::1:", 128, 32),      # stray trailing colon
        ("192.168.1.256", 128, 32),     # octet out of range
        ("", 128, 32),                  # empty
        # v4_prefix must apply to an IPv4-MAPPED address too, or a dual-stack
        # client gets a different grant key than the same client over plain IPv4.
        ("::ffff:192.168.5.77", 128, 24),
        ("192.168.5.77", 128, 24),
        # A zone is a link-scope selector, not part of the address, and for the
        # mapped form collapsing to IPv4 would silently DISCARD it.
        ("fe80::1%eth0", 128, 32),
        # Prefix bounds. All three references now fail closed on nonsense config
        # rather than reinterpreting it, so a typo cannot mean /128 on one engine
        # and a site-wide denial on another.
        ("2001:db8::1", 200, 32),
        ("1.2.3.4", 128, 64),
    ]
    for addr, p6, p4 in ip_cases:
        # Rejection is expressed as a structured `valid: false`, never as prose.
        # The old form put the Python `ipaddress` exception TEXT in `out`, which
        # no other language can reproduce byte-for-byte — so every consumer
        # improvised, and the Lua runner simply SKIPPED those entries. That left
        # the leading-zero rejection (PROTOCOL §4 step 1) untested in the
        # implementation that actually runs in production BunkerWeb.
        entry = {"in": addr, "v6_prefix": p6, "v4_prefix": p4}
        try:
            entry["out"] = canon_ip(addr, p6, p4)
            entry["valid"] = True
        except ValueError as e:
            entry["out"] = None
            entry["valid"] = False
            if not (0 <= p6 <= 128 and 0 <= p4 <= 32):
                entry["reason"] = "prefix-out-of-range"
                v["canon_ip"].append(entry)
                continue
            # NOT the exception text: that is a CPython string, and --check diffs
            # this file byte-for-byte, so embedding it would re-couple the vectors
            # to one interpreter's wording — exactly what `valid` replaced.
            entry["reason"] = classify_rejection(addr)
        v["canon_ip"].append(entry)

    # --- proof ---
    secret = bytes(range(32))  # 00,01,...,1f
    proof_cases = [
        ("grafana.example.com", "kid_AAAAAAAAAAAAAAAAAAAA", bytes(range(56))),
        ("wiki.internal",       "kid_BBBBBBBBBBBBBBBBBBBB", bytes([0x11]) * 56),
        # cross-service isolation witness: same secret+kid+nonce, different service
        ("grafana.example.com", "kid_shared",              bytes([0x22]) * 56),
        ("9wiki.internal",      "kid_shared",              bytes([0x22]) * 56),
    ]
    for server_name, kid, nonce_raw in proof_cases:
        tag, canonical = build_proof(secret, server_name, kid, nonce_raw)
        v["proof"].append({
            "secret_hex": hexs(secret),
            "server_name": server_name,
            "server_name_canon": canon_server_name(server_name),
            "kid": kid,
            "nonce_raw_hex": hexs(nonce_raw),
            "nonce_b64url": b64u(nonce_raw),
            "canonical_hex": hexs(canonical),
            "proof_b64url": b64u(tag),
        })

    # --- nonce ---
    nonce_key = bytes([0xAB]) * 32
    nonce_cases = [
        (1_700_000_000, bytes(range(16)),          "grafana.example.com", "1.2.3.4",   128),
        (1_700_000_000, bytes([0xCD]) * 16,        "wiki.internal",       "2001:db8::1", 128),
        (1_700_000_000, bytes([0xEF]) * 16,        "app.example.com",     "2001:db8:abcd:1234::99", 64),
    ]
    for ts, rand, server_name, ip, p6 in nonce_cases:
        nonce = build_nonce(nonce_key, ts, rand, server_name, ip, p6)
        ok, got_rand = verify_nonce(nonce_key, nonce, server_name, ip, ts + 5, 60, p6)
        v["nonce"].append({
            "nonce_key_hex": hexs(nonce_key),
            "ts": ts,
            "rand_hex": hexs(rand),
            "server_name": server_name,
            "server_name_canon": canon_server_name(server_name),
            "ip": ip,
            "ip_canon": canon_ip(ip, p6),
            "v6_prefix": p6,
            "nonce_hex": hexs(nonce),
            "nonce_b64url": b64u(nonce),
            "verify_at_ts_plus_5_ttl_60": ok,
        })

    return v


def openssl_cross_check(vectors: dict, strict: bool = False) -> None:
    """Independently recompute the first proof tag with the openssl CLI as a
    second witness that our HMAC is standard HMAC-SHA256 over the canonical bytes."""
    import shutil, subprocess, tempfile
    if not shutil.which("openssl"):
        # Under --check this is the ONLY witness in this script that is not the
        # implementation under test (everything else imports core/py/jitcrypto),
        # so skipping it silently would let --check report success while proving
        # nothing beyond "the file matches what this code just produced".
        if strict:
            print("  ERROR: --check needs openssl for the independent HMAC cross-check")
            sys.exit(1)
        print("  (openssl not found; skipping cross-check)")
        return
    case = vectors["proof"][0]
    canonical = bytes.fromhex(case["canonical_hex"])
    key_hex = case["secret_hex"]
    with tempfile.NamedTemporaryFile(delete=False) as f:
        f.write(canonical)
        path = f.name
    try:
        out = subprocess.check_output(
            ["openssl", "dgst", "-sha256", "-mac", "HMAC", "-macopt", f"hexkey:{key_hex}", path],
            text=True,
        )
        tag_hex = out.strip().rsplit(" ", 1)[-1]
        ours_hex = b64u_dec(case["proof_b64url"]).hex()
        status = "MATCH" if tag_hex == ours_hex else "MISMATCH"
        print(f"  openssl HMAC cross-check: {status}")
        if tag_hex != ours_hex:
            print(f"    openssl={tag_hex}\n    ours   ={ours_hex}")
            sys.exit(1)
    finally:
        os.unlink(path)


def self_test() -> None:
    """A few invariants that must hold regardless of the vectors."""
    # PAE injectivity on the classic collision pair
    assert pae([b"aa", b"bb"]) != pae([b"aab", b"b"]), "PAE not injective!"
    # proof verify round-trip
    secret = b"\x01" * 32
    tag, _ = build_proof(secret, "svc.example.com", "kid_x", b"\x00" * 56)
    assert verify_proof(secret, "svc.example.com", "kid_x", b"\x00" * 56, tag)
    # wrong service must not verify (cross-service isolation)
    assert not verify_proof(secret, "other.example.com", "kid_x", b"\x00" * 56, tag)
    # nonce round-trip + binding
    nk = b"\x02" * 32
    n = build_nonce(nk, 1000, b"\x03" * 16, "svc.example.com", "1.2.3.4")
    ok, rand = verify_nonce(nk, n, "svc.example.com", "1.2.3.4", 1005, 60)
    assert ok and rand == b"\x03" * 16
    # wrong IP must fail the nonce binding
    ok2, _ = verify_nonce(nk, n, "svc.example.com", "9.9.9.9", 1005, 60)
    assert not ok2
    # expired nonce fails
    ok3, _ = verify_nonce(nk, n, "svc.example.com", "1.2.3.4", 2000, 60)
    assert not ok3
    print("  self-test: PASS (PAE injective, proof binds service, nonce binds ip+ttl)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="diff against the committed vectors.json")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "vectors.json")

    print("Generating JIT Network Access conformance vectors...")
    self_test()
    vectors = build_vectors()
    openssl_cross_check(vectors, strict=args.check)
    rendered = json.dumps(vectors, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        with open(out_path, encoding="utf-8") as f:
            existing = f.read()
        if existing != rendered:
            print("  DRIFT: vectors.json does not match the generator output.")
            sys.exit(1)
        print("  vectors.json is up to date.")
        return

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(rendered)
    print(f"  wrote {out_path}")
    print(f"  pae={len(vectors['pae'])} canon_server_name={len(vectors['canon_server_name'])} "
          f"canon_ip={len(vectors['canon_ip'])} proof={len(vectors['proof'])} nonce={len(vectors['nonce'])}")


if __name__ == "__main__":
    main()
